import Head from "next/head";
import Image from "next/image";
// import * as React from 'react';
// import Card from '@mui/material/Card';
// import CardActions from '@mui/material/CardActions';
// import CardContent from '@mui/material/CardContent';
// import CardMedia from '@mui/material/CardMedia';
// import Button from '@mui/material/Button';
// import Typography from '@mui/material/Typography';





export default function AddToCart() {
    return(
        <>
        <Head>
            <title>Add to Cart | shop-next</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/shop-next logo.png" />
        </Head>

        <main className={styles.body}>
            <div className={styles.container}>
                <div className={styles.templates}>
                {/* <Card sx={{ maxWidth: 345 }}>
            <CardMedia
              sx={{ height: 140 }}
              image="/waec.png"
            />
            <CardContent>
              <Typography gutterBottom variant="h5" component="div" className='text-3xl text-bold text-right'>
                WAEC
              </Typography>
              <Typography variant="body2" color="text.secondary" className='text-right'>
                  The West African Examnination Council
              </Typography>
            </CardContent>
            </Card> */}
          

                </div>
            </div>

        </main>
        </>

    )
    
}

const styles = {
    body:'',
    container:'',
    templates:'',

}